In [72]:
import cv2 as cv

#Nalozimo slike
img1 = cv.imread("0_908_08052022_SLIKA OBRABE.JPG")
img2 = cv.imread("3_718_08052022_SLIKA OBRABE.JPG")

print (img1.shape)
print (img2.shape)
#Slike niso iste velikosti

(753, 1215, 3)
(753, 1227, 3)


In [73]:
# print(len(img1[1]))
img1 = img1[:, :len(img1[1]) - 100]
grayscale = cv.cvtColor(img1, cv.COLOR_BGR2GRAY)
ret, thresholded = cv.threshold(grayscale, 100, 255, cv.THRESH_BINARY_INV)
cv.imwrite("otsu.png", thresholded)
bbox = cv.boundingRect(thresholded)
x, y, w, h = bbox
print(bbox)
foreground = img1[y:y+h, x:x+w]
cv.imwrite("foreground.png", foreground)

(6, 10, 1096, 734)


True

## ZELIM OBREZAT SLIKO, DA OSTANE SAMO VLOZEK, OD ROBA DO ROBA
Brisem vrstice in stolpce pikslov ob straneh slike, dokler se tej ujemajo (siva barva)

In [74]:
import numpy as np

# Dokler je stolpec iste barve ga brisemo
brisi = True
while brisi == True:
    for vrstica in range(len(img1) - 10):
        #Preverimo ce gre za isto barvo v celem stolpcu (v meji tolerance, ker ni ista siva barva cez cel stolpec)
        # 10% toleranca ujemanja. Če se barva razlikuje za manj kot 10%, smatramo kot ista barva
        if np.allclose(img1[vrstica][0], img1[vrstica + 10][0], rtol=10e-2, equal_nan=False) == False:
            print("Neujemanje!")
            print(img1[vrstica][0])
            print(img1[vrstica + 1][0])
            brisi = False
    print("Ke kaco")
    if brisi:
        print ("Brisanje stolpca!")
        print (img1.shape)
        img1 = img1[1:,:,:]
        print ("after: ", img1.shape)

Neujemanje!
[200 177 181]
[200 177 181]
Neujemanje!
[200 177 181]
[200 177 182]
Neujemanje!
[200 177 182]
[199 177 182]
Neujemanje!
[199 177 182]
[197 176 184]
Neujemanje!
[197 176 184]
[193 177 184]
Neujemanje!
[204 185 194]
[195 178 189]
Ke kaco


In [75]:
#so resize one image to the size of the other before adding
img2=cv.resize(img2, (3000,4000))#add(or blend) the images
result = cv.addWeighted(img1, 0.3, img2, 0.7, 0)#create a resizable window for the image
cv.namedWindow('result',cv.WINDOW_NORMAL)#show the image on the screen
cv.imshow('result',result)
if cv.waitKey()==0:
    cv.destroyAllWindows()

error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'
